// copyright: Copyright (c) 2024 Lowell D. Thomas, all rights reserved<br>
//   license: BSD-2-Clause (https://opensource.org/licenses/BSD-2-Clause)<br>
//
// Generated by apg-js, Version 4.4.0 [apg-js](https://github.com/ldthomas/apg-js)
export default function grammar(){
  // ```
  // SUMMARY
  //      rules = 36
  //       udts = 0
  //    opcodes = 212
  //        ---   ABNF original opcodes
  //        ALT = 21
  //        CAT = 24
  //        REP = 16
  //        RNM = 55
  //        TLS = 72
  //        TBS = 12
  //        TRG = 12
  //        ---   SABNF superset opcodes
  //        UDT = 0
  //        AND = 0
  //        NOT = 0
  // characters = [0 - 1114111]
  // ```
  /* OBJECT IDENTIFIER (for internal parser use) */
  this.grammarObject = 'grammarObject';

  /* RULES */
  this.rules = [];
  this.rules[0] = { name: 'expression', lower: 'expression', index: 0, isBkr: false };
  this.rules[1] = { name: 'source', lower: 'source', index: 1, isBkr: false };
  this.rules[2] = { name: 'header-reference', lower: 'header-reference', index: 2, isBkr: false };
  this.rules[3] = { name: 'query-reference', lower: 'query-reference', index: 3, isBkr: false };
  this.rules[4] = { name: 'path-reference', lower: 'path-reference', index: 4, isBkr: false };
  this.rules[5] = { name: 'body-reference', lower: 'body-reference', index: 5, isBkr: false };
  this.rules[6] = { name: 'name', lower: 'name', index: 6, isBkr: false };
  this.rules[7] = { name: 'expression-string', lower: 'expression-string', index: 7, isBkr: false };
  this.rules[8] = { name: 'embedded-expression', lower: 'embedded-expression', index: 8, isBkr: false };
  this.rules[9] = { name: 'literal-char', lower: 'literal-char', index: 9, isBkr: false };
  this.rules[10] = { name: 'steps-name', lower: 'steps-name', index: 10, isBkr: false };
  this.rules[11] = { name: 'steps-id', lower: 'steps-id', index: 11, isBkr: false };
  this.rules[12] = { name: 'steps-field', lower: 'steps-field', index: 12, isBkr: false };
  this.rules[13] = { name: 'steps-sub-field', lower: 'steps-sub-field', index: 13, isBkr: false };
  this.rules[14] = { name: 'workflows-name', lower: 'workflows-name', index: 14, isBkr: false };
  this.rules[15] = { name: 'workflows-id', lower: 'workflows-id', index: 15, isBkr: false };
  this.rules[16] = { name: 'workflows-field', lower: 'workflows-field', index: 16, isBkr: false };
  this.rules[17] = { name: 'workflows-sub-field', lower: 'workflows-sub-field', index: 17, isBkr: false };
  this.rules[18] = { name: 'source-descriptions-name', lower: 'source-descriptions-name', index: 18, isBkr: false };
  this.rules[19] = { name: 'source-descriptions-source-name', lower: 'source-descriptions-source-name', index: 19, isBkr: false };
  this.rules[20] = { name: 'source-descriptions-reference', lower: 'source-descriptions-reference', index: 20, isBkr: false };
  this.rules[21] = { name: 'components-name', lower: 'components-name', index: 21, isBkr: false };
  this.rules[22] = { name: 'components-field', lower: 'components-field', index: 22, isBkr: false };
  this.rules[23] = { name: 'components-sub-field', lower: 'components-sub-field', index: 23, isBkr: false };
  this.rules[24] = { name: 'json-pointer', lower: 'json-pointer', index: 24, isBkr: false };
  this.rules[25] = { name: 'reference-token', lower: 'reference-token', index: 25, isBkr: false };
  this.rules[26] = { name: 'unescaped', lower: 'unescaped', index: 26, isBkr: false };
  this.rules[27] = { name: 'escaped', lower: 'escaped', index: 27, isBkr: false };
  this.rules[28] = { name: 'token', lower: 'token', index: 28, isBkr: false };
  this.rules[29] = { name: 'tchar', lower: 'tchar', index: 29, isBkr: false };
  this.rules[30] = { name: 'CHAR', lower: 'char', index: 30, isBkr: false };
  this.rules[31] = { name: 'escape', lower: 'escape', index: 31, isBkr: false };
  this.rules[32] = { name: 'unescape', lower: 'unescape', index: 32, isBkr: false };
  this.rules[33] = { name: 'HEXDIG', lower: 'hexdig', index: 33, isBkr: false };
  this.rules[34] = { name: 'DIGIT', lower: 'digit', index: 34, isBkr: false };
  this.rules[35] = { name: 'ALPHA', lower: 'alpha', index: 35, isBkr: false };

  /* UDTS */
  this.udts = [];

  /* OPCODES */
  /* expression */
  this.rules[0].opcodes = [];
  this.rules[0].opcodes[0] = { type: 1, children: [1,2,3,4,7,10,13,16,19,22,25] };// ALT
  this.rules[0].opcodes[1] = { type: 7, string: [36,117,114,108] };// TLS
  this.rules[0].opcodes[2] = { type: 7, string: [36,109,101,116,104,111,100] };// TLS
  this.rules[0].opcodes[3] = { type: 7, string: [36,115,116,97,116,117,115,99,111,100,101] };// TLS
  this.rules[0].opcodes[4] = { type: 2, children: [5,6] };// CAT
  this.rules[0].opcodes[5] = { type: 7, string: [36,114,101,113,117,101,115,116,46] };// TLS
  this.rules[0].opcodes[6] = { type: 4, index: 1 };// RNM(source)
  this.rules[0].opcodes[7] = { type: 2, children: [8,9] };// CAT
  this.rules[0].opcodes[8] = { type: 7, string: [36,114,101,115,112,111,110,115,101,46] };// TLS
  this.rules[0].opcodes[9] = { type: 4, index: 1 };// RNM(source)
  this.rules[0].opcodes[10] = { type: 2, children: [11,12] };// CAT
  this.rules[0].opcodes[11] = { type: 7, string: [36,105,110,112,117,116,115,46] };// TLS
  this.rules[0].opcodes[12] = { type: 4, index: 6 };// RNM(name)
  this.rules[0].opcodes[13] = { type: 2, children: [14,15] };// CAT
  this.rules[0].opcodes[14] = { type: 7, string: [36,111,117,116,112,117,116,115,46] };// TLS
  this.rules[0].opcodes[15] = { type: 4, index: 6 };// RNM(name)
  this.rules[0].opcodes[16] = { type: 2, children: [17,18] };// CAT
  this.rules[0].opcodes[17] = { type: 7, string: [36,115,116,101,112,115,46] };// TLS
  this.rules[0].opcodes[18] = { type: 4, index: 6 };// RNM(name)
  this.rules[0].opcodes[19] = { type: 2, children: [20,21] };// CAT
  this.rules[0].opcodes[20] = { type: 7, string: [36,119,111,114,107,102,108,111,119,115,46] };// TLS
  this.rules[0].opcodes[21] = { type: 4, index: 6 };// RNM(name)
  this.rules[0].opcodes[22] = { type: 2, children: [23,24] };// CAT
  this.rules[0].opcodes[23] = { type: 7, string: [36,115,111,117,114,99,101,100,101,115,99,114,105,112,116,105,111,110,115,46] };// TLS
  this.rules[0].opcodes[24] = { type: 4, index: 6 };// RNM(name)
  this.rules[0].opcodes[25] = { type: 2, children: [26,27] };// CAT
  this.rules[0].opcodes[26] = { type: 7, string: [36,99,111,109,112,111,110,101,110,116,115,46] };// TLS
  this.rules[0].opcodes[27] = { type: 4, index: 6 };// RNM(name)

  /* source */
  this.rules[1].opcodes = [];
  this.rules[1].opcodes[0] = { type: 1, children: [1,2,3,4] };// ALT
  this.rules[1].opcodes[1] = { type: 4, index: 2 };// RNM(header-reference)
  this.rules[1].opcodes[2] = { type: 4, index: 3 };// RNM(query-reference)
  this.rules[1].opcodes[3] = { type: 4, index: 4 };// RNM(path-reference)
  this.rules[1].opcodes[4] = { type: 4, index: 5 };// RNM(body-reference)

  /* header-reference */
  this.rules[2].opcodes = [];
  this.rules[2].opcodes[0] = { type: 2, children: [1,2] };// CAT
  this.rules[2].opcodes[1] = { type: 7, string: [104,101,97,100,101,114,46] };// TLS
  this.rules[2].opcodes[2] = { type: 4, index: 28 };// RNM(token)

  /* query-reference */
  this.rules[3].opcodes = [];
  this.rules[3].opcodes[0] = { type: 2, children: [1,2] };// CAT
  this.rules[3].opcodes[1] = { type: 7, string: [113,117,101,114,121,46] };// TLS
  this.rules[3].opcodes[2] = { type: 4, index: 6 };// RNM(name)

  /* path-reference */
  this.rules[4].opcodes = [];
  this.rules[4].opcodes[0] = { type: 2, children: [1,2] };// CAT
  this.rules[4].opcodes[1] = { type: 7, string: [112,97,116,104,46] };// TLS
  this.rules[4].opcodes[2] = { type: 4, index: 6 };// RNM(name)

  /* body-reference */
  this.rules[5].opcodes = [];
  this.rules[5].opcodes[0] = { type: 2, children: [1,2] };// CAT
  this.rules[5].opcodes[1] = { type: 7, string: [98,111,100,121] };// TLS
  this.rules[5].opcodes[2] = { type: 3, min: 0, max: 1 };// REP
  this.rules[5].opcodes[3] = { type: 2, children: [4,5] };// CAT
  this.rules[5].opcodes[4] = { type: 7, string: [35] };// TLS
  this.rules[5].opcodes[5] = { type: 4, index: 24 };// RNM(json-pointer)

  /* name */
  this.rules[6].opcodes = [];
  this.rules[6].opcodes[0] = { type: 3, min: 0, max: Infinity };// REP
  this.rules[6].opcodes[1] = { type: 4, index: 30 };// RNM(CHAR)

  /* expression-string */
  this.rules[7].opcodes = [];
  this.rules[7].opcodes[0] = { type: 3, min: 0, max: Infinity };// REP
  this.rules[7].opcodes[1] = { type: 1, children: [2,3] };// ALT
  this.rules[7].opcodes[2] = { type: 4, index: 9 };// RNM(literal-char)
  this.rules[7].opcodes[3] = { type: 4, index: 8 };// RNM(embedded-expression)

  /* embedded-expression */
  this.rules[8].opcodes = [];
  this.rules[8].opcodes[0] = { type: 2, children: [1,2,3] };// CAT
  this.rules[8].opcodes[1] = { type: 7, string: [123] };// TLS
  this.rules[8].opcodes[2] = { type: 4, index: 0 };// RNM(expression)
  this.rules[8].opcodes[3] = { type: 7, string: [125] };// TLS

  /* literal-char */
  this.rules[9].opcodes = [];
  this.rules[9].opcodes[0] = { type: 1, children: [1,2,3] };// ALT
  this.rules[9].opcodes[1] = { type: 5, min: 0, max: 122 };// TRG
  this.rules[9].opcodes[2] = { type: 6, string: [124] };// TBS
  this.rules[9].opcodes[3] = { type: 5, min: 126, max: 1114111 };// TRG

  /* steps-name */
  this.rules[10].opcodes = [];
  this.rules[10].opcodes[0] = { type: 2, children: [1,2,3,4,5,6] };// CAT
  this.rules[10].opcodes[1] = { type: 4, index: 11 };// RNM(steps-id)
  this.rules[10].opcodes[2] = { type: 7, string: [46] };// TLS
  this.rules[10].opcodes[3] = { type: 4, index: 12 };// RNM(steps-field)
  this.rules[10].opcodes[4] = { type: 7, string: [46] };// TLS
  this.rules[10].opcodes[5] = { type: 4, index: 13 };// RNM(steps-sub-field)
  this.rules[10].opcodes[6] = { type: 3, min: 0, max: 1 };// REP
  this.rules[10].opcodes[7] = { type: 2, children: [8,9] };// CAT
  this.rules[10].opcodes[8] = { type: 7, string: [35] };// TLS
  this.rules[10].opcodes[9] = { type: 4, index: 24 };// RNM(json-pointer)

  /* steps-id */
  this.rules[11].opcodes = [];
  this.rules[11].opcodes[0] = { type: 3, min: 1, max: Infinity };// REP
  this.rules[11].opcodes[1] = { type: 1, children: [2,3,4,5] };// ALT
  this.rules[11].opcodes[2] = { type: 4, index: 35 };// RNM(ALPHA)
  this.rules[11].opcodes[3] = { type: 4, index: 34 };// RNM(DIGIT)
  this.rules[11].opcodes[4] = { type: 7, string: [95] };// TLS
  this.rules[11].opcodes[5] = { type: 7, string: [45] };// TLS

  /* steps-field */
  this.rules[12].opcodes = [];
  this.rules[12].opcodes[0] = { type: 7, string: [111,117,116,112,117,116,115] };// TLS

  /* steps-sub-field */
  this.rules[13].opcodes = [];
  this.rules[13].opcodes[0] = { type: 3, min: 1, max: Infinity };// REP
  this.rules[13].opcodes[1] = { type: 1, children: [2,3,4,5,6] };// ALT
  this.rules[13].opcodes[2] = { type: 4, index: 35 };// RNM(ALPHA)
  this.rules[13].opcodes[3] = { type: 4, index: 34 };// RNM(DIGIT)
  this.rules[13].opcodes[4] = { type: 7, string: [46] };// TLS
  this.rules[13].opcodes[5] = { type: 7, string: [45] };// TLS
  this.rules[13].opcodes[6] = { type: 7, string: [95] };// TLS

  /* workflows-name */
  this.rules[14].opcodes = [];
  this.rules[14].opcodes[0] = { type: 2, children: [1,2,3,4,5,6] };// CAT
  this.rules[14].opcodes[1] = { type: 4, index: 15 };// RNM(workflows-id)
  this.rules[14].opcodes[2] = { type: 7, string: [46] };// TLS
  this.rules[14].opcodes[3] = { type: 4, index: 16 };// RNM(workflows-field)
  this.rules[14].opcodes[4] = { type: 7, string: [46] };// TLS
  this.rules[14].opcodes[5] = { type: 4, index: 17 };// RNM(workflows-sub-field)
  this.rules[14].opcodes[6] = { type: 3, min: 0, max: 1 };// REP
  this.rules[14].opcodes[7] = { type: 2, children: [8,9] };// CAT
  this.rules[14].opcodes[8] = { type: 7, string: [35] };// TLS
  this.rules[14].opcodes[9] = { type: 4, index: 24 };// RNM(json-pointer)

  /* workflows-id */
  this.rules[15].opcodes = [];
  this.rules[15].opcodes[0] = { type: 3, min: 1, max: Infinity };// REP
  this.rules[15].opcodes[1] = { type: 1, children: [2,3,4,5] };// ALT
  this.rules[15].opcodes[2] = { type: 4, index: 35 };// RNM(ALPHA)
  this.rules[15].opcodes[3] = { type: 4, index: 34 };// RNM(DIGIT)
  this.rules[15].opcodes[4] = { type: 7, string: [95] };// TLS
  this.rules[15].opcodes[5] = { type: 7, string: [45] };// TLS

  /* workflows-field */
  this.rules[16].opcodes = [];
  this.rules[16].opcodes[0] = { type: 1, children: [1,2] };// ALT
  this.rules[16].opcodes[1] = { type: 7, string: [105,110,112,117,116,115] };// TLS
  this.rules[16].opcodes[2] = { type: 7, string: [111,117,116,112,117,116,115] };// TLS

  /* workflows-sub-field */
  this.rules[17].opcodes = [];
  this.rules[17].opcodes[0] = { type: 3, min: 1, max: Infinity };// REP
  this.rules[17].opcodes[1] = { type: 1, children: [2,3,4,5,6] };// ALT
  this.rules[17].opcodes[2] = { type: 4, index: 35 };// RNM(ALPHA)
  this.rules[17].opcodes[3] = { type: 4, index: 34 };// RNM(DIGIT)
  this.rules[17].opcodes[4] = { type: 7, string: [46] };// TLS
  this.rules[17].opcodes[5] = { type: 7, string: [45] };// TLS
  this.rules[17].opcodes[6] = { type: 7, string: [95] };// TLS

  /* source-descriptions-name */
  this.rules[18].opcodes = [];
  this.rules[18].opcodes[0] = { type: 2, children: [1,2,3] };// CAT
  this.rules[18].opcodes[1] = { type: 4, index: 19 };// RNM(source-descriptions-source-name)
  this.rules[18].opcodes[2] = { type: 7, string: [46] };// TLS
  this.rules[18].opcodes[3] = { type: 4, index: 20 };// RNM(source-descriptions-reference)

  /* source-descriptions-source-name */
  this.rules[19].opcodes = [];
  this.rules[19].opcodes[0] = { type: 3, min: 1, max: Infinity };// REP
  this.rules[19].opcodes[1] = { type: 1, children: [2,3,4,5] };// ALT
  this.rules[19].opcodes[2] = { type: 4, index: 35 };// RNM(ALPHA)
  this.rules[19].opcodes[3] = { type: 4, index: 34 };// RNM(DIGIT)
  this.rules[19].opcodes[4] = { type: 7, string: [95] };// TLS
  this.rules[19].opcodes[5] = { type: 7, string: [45] };// TLS

  /* source-descriptions-reference */
  this.rules[20].opcodes = [];
  this.rules[20].opcodes[0] = { type: 3, min: 1, max: Infinity };// REP
  this.rules[20].opcodes[1] = { type: 4, index: 30 };// RNM(CHAR)

  /* components-name */
  this.rules[21].opcodes = [];
  this.rules[21].opcodes[0] = { type: 2, children: [1,2,3] };// CAT
  this.rules[21].opcodes[1] = { type: 4, index: 22 };// RNM(components-field)
  this.rules[21].opcodes[2] = { type: 7, string: [46] };// TLS
  this.rules[21].opcodes[3] = { type: 4, index: 23 };// RNM(components-sub-field)

  /* components-field */
  this.rules[22].opcodes = [];
  this.rules[22].opcodes[0] = { type: 1, children: [1,2,3] };// ALT
  this.rules[22].opcodes[1] = { type: 7, string: [112,97,114,97,109,101,116,101,114,115] };// TLS
  this.rules[22].opcodes[2] = { type: 7, string: [115,117,99,99,101,115,115,97,99,116,105,111,110,115] };// TLS
  this.rules[22].opcodes[3] = { type: 7, string: [102,97,105,108,117,114,101,97,99,116,105,111,110,115] };// TLS

  /* components-sub-field */
  this.rules[23].opcodes = [];
  this.rules[23].opcodes[0] = { type: 3, min: 1, max: Infinity };// REP
  this.rules[23].opcodes[1] = { type: 1, children: [2,3,4,5,6] };// ALT
  this.rules[23].opcodes[2] = { type: 4, index: 35 };// RNM(ALPHA)
  this.rules[23].opcodes[3] = { type: 4, index: 34 };// RNM(DIGIT)
  this.rules[23].opcodes[4] = { type: 7, string: [46] };// TLS
  this.rules[23].opcodes[5] = { type: 7, string: [45] };// TLS
  this.rules[23].opcodes[6] = { type: 7, string: [95] };// TLS

  /* json-pointer */
  this.rules[24].opcodes = [];
  this.rules[24].opcodes[0] = { type: 3, min: 0, max: Infinity };// REP
  this.rules[24].opcodes[1] = { type: 2, children: [2,3] };// CAT
  this.rules[24].opcodes[2] = { type: 7, string: [47] };// TLS
  this.rules[24].opcodes[3] = { type: 4, index: 25 };// RNM(reference-token)

  /* reference-token */
  this.rules[25].opcodes = [];
  this.rules[25].opcodes[0] = { type: 3, min: 0, max: Infinity };// REP
  this.rules[25].opcodes[1] = { type: 1, children: [2,3] };// ALT
  this.rules[25].opcodes[2] = { type: 4, index: 26 };// RNM(unescaped)
  this.rules[25].opcodes[3] = { type: 4, index: 27 };// RNM(escaped)

  /* unescaped */
  this.rules[26].opcodes = [];
  this.rules[26].opcodes[0] = { type: 1, children: [1,2,3] };// ALT
  this.rules[26].opcodes[1] = { type: 5, min: 0, max: 46 };// TRG
  this.rules[26].opcodes[2] = { type: 5, min: 48, max: 125 };// TRG
  this.rules[26].opcodes[3] = { type: 5, min: 127, max: 1114111 };// TRG

  /* escaped */
  this.rules[27].opcodes = [];
  this.rules[27].opcodes[0] = { type: 2, children: [1,2] };// CAT
  this.rules[27].opcodes[1] = { type: 7, string: [126] };// TLS
  this.rules[27].opcodes[2] = { type: 1, children: [3,4] };// ALT
  this.rules[27].opcodes[3] = { type: 7, string: [48] };// TLS
  this.rules[27].opcodes[4] = { type: 7, string: [49] };// TLS

  /* token */
  this.rules[28].opcodes = [];
  this.rules[28].opcodes[0] = { type: 3, min: 1, max: Infinity };// REP
  this.rules[28].opcodes[1] = { type: 4, index: 29 };// RNM(tchar)

  /* tchar */
  this.rules[29].opcodes = [];
  this.rules[29].opcodes[0] = { type: 1, children: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17] };// ALT
  this.rules[29].opcodes[1] = { type: 7, string: [33] };// TLS
  this.rules[29].opcodes[2] = { type: 7, string: [35] };// TLS
  this.rules[29].opcodes[3] = { type: 7, string: [36] };// TLS
  this.rules[29].opcodes[4] = { type: 7, string: [37] };// TLS
  this.rules[29].opcodes[5] = { type: 7, string: [38] };// TLS
  this.rules[29].opcodes[6] = { type: 7, string: [39] };// TLS
  this.rules[29].opcodes[7] = { type: 7, string: [42] };// TLS
  this.rules[29].opcodes[8] = { type: 7, string: [43] };// TLS
  this.rules[29].opcodes[9] = { type: 7, string: [45] };// TLS
  this.rules[29].opcodes[10] = { type: 7, string: [46] };// TLS
  this.rules[29].opcodes[11] = { type: 7, string: [94] };// TLS
  this.rules[29].opcodes[12] = { type: 7, string: [95] };// TLS
  this.rules[29].opcodes[13] = { type: 7, string: [96] };// TLS
  this.rules[29].opcodes[14] = { type: 7, string: [124] };// TLS
  this.rules[29].opcodes[15] = { type: 7, string: [126] };// TLS
  this.rules[29].opcodes[16] = { type: 4, index: 34 };// RNM(DIGIT)
  this.rules[29].opcodes[17] = { type: 4, index: 35 };// RNM(ALPHA)

  /* CHAR */
  this.rules[30].opcodes = [];
  this.rules[30].opcodes[0] = { type: 1, children: [1,2] };// ALT
  this.rules[30].opcodes[1] = { type: 4, index: 32 };// RNM(unescape)
  this.rules[30].opcodes[2] = { type: 2, children: [3,4] };// CAT
  this.rules[30].opcodes[3] = { type: 4, index: 31 };// RNM(escape)
  this.rules[30].opcodes[4] = { type: 1, children: [5,6,7,8,9,10,11,12,13] };// ALT
  this.rules[30].opcodes[5] = { type: 6, string: [34] };// TBS
  this.rules[30].opcodes[6] = { type: 6, string: [92] };// TBS
  this.rules[30].opcodes[7] = { type: 6, string: [47] };// TBS
  this.rules[30].opcodes[8] = { type: 6, string: [98] };// TBS
  this.rules[30].opcodes[9] = { type: 6, string: [102] };// TBS
  this.rules[30].opcodes[10] = { type: 6, string: [110] };// TBS
  this.rules[30].opcodes[11] = { type: 6, string: [114] };// TBS
  this.rules[30].opcodes[12] = { type: 6, string: [116] };// TBS
  this.rules[30].opcodes[13] = { type: 2, children: [14,15] };// CAT
  this.rules[30].opcodes[14] = { type: 6, string: [117] };// TBS
  this.rules[30].opcodes[15] = { type: 3, min: 4, max: 4 };// REP
  this.rules[30].opcodes[16] = { type: 4, index: 33 };// RNM(HEXDIG)

  /* escape */
  this.rules[31].opcodes = [];
  this.rules[31].opcodes[0] = { type: 6, string: [92] };// TBS

  /* unescape */
  this.rules[32].opcodes = [];
  this.rules[32].opcodes[0] = { type: 1, children: [1,2,3,4,5] };// ALT
  this.rules[32].opcodes[1] = { type: 5, min: 32, max: 33 };// TRG
  this.rules[32].opcodes[2] = { type: 5, min: 35, max: 91 };// TRG
  this.rules[32].opcodes[3] = { type: 5, min: 93, max: 122 };// TRG
  this.rules[32].opcodes[4] = { type: 6, string: [124] };// TBS
  this.rules[32].opcodes[5] = { type: 5, min: 126, max: 1114111 };// TRG

  /* HEXDIG */
  this.rules[33].opcodes = [];
  this.rules[33].opcodes[0] = { type: 1, children: [1,2,3,4,5,6,7] };// ALT
  this.rules[33].opcodes[1] = { type: 4, index: 34 };// RNM(DIGIT)
  this.rules[33].opcodes[2] = { type: 7, string: [97] };// TLS
  this.rules[33].opcodes[3] = { type: 7, string: [98] };// TLS
  this.rules[33].opcodes[4] = { type: 7, string: [99] };// TLS
  this.rules[33].opcodes[5] = { type: 7, string: [100] };// TLS
  this.rules[33].opcodes[6] = { type: 7, string: [101] };// TLS
  this.rules[33].opcodes[7] = { type: 7, string: [102] };// TLS

  /* DIGIT */
  this.rules[34].opcodes = [];
  this.rules[34].opcodes[0] = { type: 5, min: 48, max: 57 };// TRG

  /* ALPHA */
  this.rules[35].opcodes = [];
  this.rules[35].opcodes[0] = { type: 1, children: [1,2] };// ALT
  this.rules[35].opcodes[1] = { type: 5, min: 65, max: 90 };// TRG
  this.rules[35].opcodes[2] = { type: 5, min: 97, max: 122 };// TRG

  // The `toString()` function will display the original grammar file(s) that produced these opcodes.
  this.toString = function toString(){
    let str = "";
    str += "; Arazzo runtime expression ABNF syntax\n";
    str += "expression       = ( \"$url\" / \"$method\" / \"$statusCode\" / \"$request.\" source / \"$response.\" source / \"$inputs.\" name / \"$outputs.\" name / \"$steps.\" name / \"$workflows.\" name / \"$sourceDescriptions.\" name / \"$components.\" name )\n";
    str += "source           = ( header-reference / query-reference / path-reference / body-reference )\n";
    str += "header-reference = \"header.\" token\n";
    str += "query-reference  = \"query.\" name\n";
    str += "path-reference   = \"path.\" name\n";
    str += "body-reference   = \"body\" [\"#\" json-pointer ]\n";
    str += "name             = *( CHAR )\n";
    str += "\n";
    str += "; Grammar for parsing template strings with embedded expressions\n";
    str += "expression-string    = *( literal-char / embedded-expression )\n";
    str += "embedded-expression  = \"{\" expression \"}\"\n";
    str += "literal-char         = %x00-7A / %x7C / %x7E-10FFFF  ; anything except { (%x7B) and } (%x7D)\n";
    str += "\n";
    str += "; Secondary grammar for parsing $steps name part\n";
    str += "; Format: {stepId}.{field}.{subField}[#/{jsonPointer}]\n";
    str += "steps-name       = steps-id \".\" steps-field \".\" steps-sub-field [\"#\" json-pointer]\n";
    str += "steps-id         = 1*(ALPHA / DIGIT / \"_\" / \"-\")\n";
    str += "steps-field      = \"outputs\"\n";
    str += "steps-sub-field  = 1*(ALPHA / DIGIT / \".\" / \"-\" / \"_\")\n";
    str += "\n";
    str += "; Secondary grammar for parsing $workflows name part\n";
    str += "; Format: {workflowId}.{field}.{subField}[#/{jsonPointer}]\n";
    str += "workflows-name       = workflows-id \".\" workflows-field \".\" workflows-sub-field [\"#\" json-pointer]\n";
    str += "workflows-id         = 1*(ALPHA / DIGIT / \"_\" / \"-\")\n";
    str += "workflows-field      = \"inputs\" / \"outputs\"\n";
    str += "workflows-sub-field  = 1*(ALPHA / DIGIT / \".\" / \"-\" / \"_\")\n";
    str += "\n";
    str += "; Secondary grammar for parsing $sourceDescriptions name part\n";
    str += "; Format: {sourceName}.{reference}\n";
    str += "; reference can be operationId (unconstrained) or workflowId (constrained)\n";
    str += "source-descriptions-name        = source-descriptions-source-name \".\" source-descriptions-reference\n";
    str += "source-descriptions-source-name = 1*(ALPHA / DIGIT / \"_\" / \"-\")\n";
    str += "source-descriptions-reference   = 1*CHAR\n";
    str += "\n";
    str += "; Secondary grammar for parsing $components name part\n";
    str += "; Format: {field}.{subField}\n";
    str += "; Allowed fields: parameters, successActions, failureActions\n";
    str += "components-name      = components-field \".\" components-sub-field\n";
    str += "components-field     = \"parameters\" / \"successActions\" / \"failureActions\"\n";
    str += "components-sub-field = 1*(ALPHA / DIGIT / \".\" / \"-\" / \"_\")\n";
    str += "\n";
    str += "; https://datatracker.ietf.org/doc/html/rfc6901#section-3\n";
    str += "json-pointer     = *( \"/\" reference-token )\n";
    str += "reference-token  = *( unescaped / escaped )\n";
    str += "unescaped        = %x00-2E / %x30-7D / %x7F-10FFFF\n";
    str += "                 ; %x2F ('/') and %x7E ('~') are excluded from 'unescaped'\n";
    str += "escaped          = \"~\" ( \"0\" / \"1\" )\n";
    str += "                 ; representing '~' and '/', respectively\n";
    str += "\n";
    str += "; https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.6\n";
    str += "token          = 1*tchar\n";
    str += "tchar          = \"!\" / \"#\" / \"$\" / \"%\" / \"&\" / \"'\" / \"*\"\n";
    str += "               / \"+\" / \"-\" / \".\" / \"^\" / \"_\" / \"`\" / \"|\" / \"~\"\n";
    str += "               / DIGIT / ALPHA\n";
    str += "               ; any VCHAR, except delimiters\n";
    str += "\n";
    str += "; https://www.rfc-editor.org/rfc/rfc7159#section-7\n";
    str += "CHAR = unescape /\n";
    str += "    escape (\n";
    str += "        %x22 /          ; \"    quotation mark  U+0022\n";
    str += "        %x5C /          ; \\    reverse solidus U+005C\n";
    str += "        %x2F /          ; /    solidus         U+002F\n";
    str += "        %x62 /          ; b    backspace       U+0008\n";
    str += "        %x66 /          ; f    form feed       U+000C\n";
    str += "        %x6E /          ; n    line feed       U+000A\n";
    str += "        %x72 /          ; r    carriage return U+000D\n";
    str += "        %x74 /          ; t    tab             U+0009\n";
    str += "        %x75 4HEXDIG )  ; uXXXX                U+XXXX\n";
    str += "escape         = %x5C   ; \\\n";
    str += "unescape       = %x20-21 / %x23-5B / %x5D-7A / %x7C / %x7E-10FFFF\n";
    str += "               ; %x7B ('{') and %x7D ('}') are excluded from 'unescape'\n";
    str += "\n";
    str += "; https://datatracker.ietf.org/doc/html/rfc5234#appendix-B.1\n";
    str += "HEXDIG         =  DIGIT / \"A\" / \"B\" / \"C\" / \"D\" / \"E\" / \"F\"\n";
    str += "DIGIT          =  %x30-39   ; 0-9\n";
    str += "ALPHA          =  %x41-5A / %x61-7A   ; A-Z / a-z\n";
    return str;
  }
}
